[package]
name = "models"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
hf-hub = { workspace = true }
image = { workspace = true }
ndarray = { workspace = true }
num-traits = { workspace = true }
ort = { workspace = true }
